In [1]:
import pandas as pd

In [3]:
silver_df = pd.read_csv("data/silver/cleaned_claims.csv")

silver_df.head(20)

,claim_id,customer_id,policy_type,claim_amount,claim_status,incident_type,state,adjuster_id,fraud_flag,claim_date,high_value_claim,high_risk_incident,suspicious_claim,claim_severity
0,1,1858,Auto,21405.32,Denied,Accident,NE,226,0,2026-05-25 10:28:28.319826,False,False,False,High
1,2,1522,Life,26014.20,Denied,Flood,FL,241,0,2026-05-25 10:28:28.319873,False,False,False,High
2,3,3387,Home,10261.01,Pending,Accident,TN,283,0,2026-05-25 10:28:28.319895,False,False,False,Medium
3,4,3155,Auto,48596.16,Pending,Flood,LA,117,0,2026-05-25 10:28:28.319908,True,False,False,Critical
4,5,3496,Life,23920.96,Approved,Flood,MD,292,0,2026-05-25 10:28:28.319923,False,False,False,High
5,6,3248,Life,30712.12,Approved,Accident,VA,172,0,2026-05-25 10:28:28.319936,True,False,False,High
6,7,1290,Life,9925.26,Pending,Fire,OR,162,0,2026-05-25 10:28:28.319948,False,True,False,Medium
7,8,3355,Home,49833.95,Approved,Fire,AR,159,0,2026-05-25 10:28:28.319960,True,True,True,Critical
8,9,4784,Home,2849.13,Pending,Flood,VA,173,0,2026-05-25 10:28:28.319970,False,False,False,Medium
9,10,3256,Life,48582.11,Pending,Accident,MN,175,0,2026-05-25 10:28:28.319983,True,False,False,Critical
10,11,3434,Life,10885.65,Denied,Fire,OH,219,0,2026-05-25 10:28:28.319994,False,True,False,Medium
11,12,3158,Life,1006.94,Pending,Fire,IL,297,0,2026-05-25 10:28:28.320006,False,True,False,Medium
12,13,3884,Home,8092.25,Pending,Flood,NE,148,1,2026-05-25 10:28:28.320017,False,False,True,Medium
13,14,1053,Auto,22534.03,Denied,Accident,IL,291,0,2026-05-25 10:28:28.320034,False,False,False,High
14,15,1604,Home,2167.45,Approved,Fire,OH,147,0,2026-05-25 10:28:28.320046,False,True,False,Medium
15,16,4488,Home,18547.06,Approved,Flood,VI,133,1,2026-05-25 10:28:28.320057,False,False,True,Medium
16,17,2658,Auto,18812.23,Denied,Fire,AS,236,1,2026-05-25 10:28:28.320075,False,True,True,Medium
17,18,4218,Auto,42810.74,Pending,Accident,MO,279,0,2026-05-25 10:28:28.320087,True,False,False,Critical
18,19,2060,Home,6479.21,Approved,Flood,MO,236,1,2026-05-25 10:28:28.320097,False,False,True,Medium
19,20,3441,Life,35189.37,Pending,Fire,ME,271,1,2026-05-25 10:28:28.320109,True,True,True,High

In [4]:
gold_df = pd.read_csv("data/gold/claims_kpis.csv")

gold_df

,total_claims,total_claim_amount,average_claim_amount,suspicious_claims,high_value_claims,approved_claims,denied_claims,pending_claims
0,1000,25713185.11,25713.19,416,418,313,349,338